services:
  app:
    build: .
    ports:
      - "${PORT}:3000"
    depends_on:
      - mysql
    env_file:
      - .env
  mysql:
    image: mysql:8

    container_name: iron-dome-db

    restart: always

    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
